# Generated by Django 5.1 on 2024-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('cpf', models.CharField(max_length=14)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
    ]
